"""
Cosmetic mappings for Fortnite items - converts template IDs to human-readable names
Based on the C# GlobalVariables implementation
"""

# Outfit mappings (AthenaCharacter)
OUTFITS = {
    "001_athena_commando_f_default": "Ramirez",
    "002_athena_commando_f_default": "Headhunter", 
    "003_athena_commando_f_default": "Banshee",
    "004_athena_commando_f_default": "Wildcat",
    "005_athena_commando_m_default": "Jonesy",
    "006_athena_commando_m_default": "Hawk",
    "007_athena_commando_m_default": "Spitfire",
    "008_athena_commando_m_default": "Renegade",
    "011_athena_commando_m_nutcracker": "Crackshot",
    "012_athena_commando_m_holiday": "Yuletide Ranger",
    "013_athena_commando_f_holiday": "Holly Jammer",
    "014_athena_commando_f_tactical": "Assault Trooper",
    "015_athena_commando_m_tactical": "Special Forces",
    "016_athena_commando_f_camo": "Jungle Scout",
    "017_athena_commando_m_camo": "Forest Ranger",
    "018_athena_commando_f_astronaut": "Moonwalker",
    "019_athena_commando_m_astronaut": "Mission Specialist",
    "020_athena_commando_f_space": "Dark Vanguard",
    "021_athena_commando_m_space": "Dark Voyager",
    "022_athena_commando_f_valentine": "Cuddle Team Leader",
    "023_athena_commando_f_valentine": "Love Ranger",
    "024_athena_commando_m_valentine": "Love Ranger",
    "025_athena_commando_m_scavenger": "Raptor",
    "026_athena_commando_f_scavenger": "Raven",
    "027_athena_commando_f_punk": "Power Chord",
    "028_athena_commando_m_punk": "Stage Slayer",
    "029_athena_commando_f_retro": "Funk Ops",
    "030_athena_commando_m_retro": "Disco Dude",
    "031_athena_commando_f_student": "Zoey",
    "032_athena_commando_m_student": "Highrise Assault Trooper",
    "033_athena_commando_f_medieval": "Red Knight",
    "034_athena_commando_m_medieval": "Black Knight",
    "035_athena_commando_f_pirate": "Sea Wolf",
    "036_athena_commando_m_pirate": "Blackheart",
    "037_athena_commando_f_cowboy": "Calamity",
    "038_athena_commando_m_cowboy": "Deadfire",
    "039_athena_commando_f_ninja": "Lynx",
    "040_athena_commando_m_ninja": "Drift",
    "041_athena_commando_f_cyberscavenger": "Circuit Breaker",
    "042_athena_commando_m_cyberscavenger": "Vertex",
    "043_athena_commando_f_plague": "Plague",
    "044_athena_commando_m_plague": "Scourge",
    "045_athena_commando_f_carbide": "Carbide",
    "046_athena_commando_m_carbide": "Omega",
    "047_athena_commando_f_footballer": "Clinical Crosser",
    "048_athena_commando_m_footballer": "Finesse Finisher",
    "049_athena_commando_f_soccer": "Dynamic Dribbler",
    "050_athena_commando_m_soccer": "Midfield Maestro",
    "051_athena_commando_f_basketballplayer": "Triple Threat",
    "052_athena_commando_m_basketballplayer": "Full Court",
    "053_athena_commando_f_lifeguard": "Sun Strider",
    "054_athena_commando_m_lifeguard": "Beach Bomber",
    "055_athena_commando_f_detective": "Noir",
    "056_athena_commando_m_detective": "Gumshoe",
    "057_athena_commando_f_western": "Calamity",
    "058_athena_commando_m_western": "Deadfire",
    "059_athena_commando_f_vampire": "Dusk",
    "060_athena_commando_m_vampire": "Sanctum",
    "061_athena_commando_f_streetwear": "Whiteout",
    "062_athena_commando_m_streetwear": "Overtaker",
    "063_athena_commando_f_demon": "Malice",
    "064_athena_commando_m_demon": "Ravage",
    "065_athena_commando_f_clown": "Peekaboo",
    "066_athena_commando_m_clown": "Nite Nite",
    "067_athena_commando_f_cat": "Lynx",
    "068_athena_commando_m_cat": "Meowscles",
    "069_athena_commando_f_viking": "Valkyrie",
    "070_athena_commando_m_viking": "Ragnarok",
    "071_athena_commando_f_prisoner": "The Prisoner",
    "072_athena_commando_m_prisoner": "Blackheart",
    "073_athena_commando_f_banana": "Peely",
    "074_athena_commando_m_banana": "Agent Peely",
    "075_athena_commando_f_fishstick": "Fishstick",
    "076_athena_commando_m_fishstick": "Leviathan",
    "077_athena_commando_f_robot": "Singularity",
    "078_athena_commando_m_robot": "The Scientist",
    "079_athena_commando_f_ice": "Ice Queen",
    "080_athena_commando_m_ice": "Ice King",
    "081_athena_commando_f_fire": "Ember",
    "082_athena_commando_m_fire": "Inferno",
    "083_athena_commando_f_military": "Survival Specialist",
    "084_athena_commando_m_military": "Squad Leader",
    "085_athena_commando_f_biker": "Burnout",
    "086_athena_commando_m_biker": "Redline",
    "087_athena_commando_f_skier": "Mogul Master",
    "088_athena_commando_m_skier": "Alpine Ace",
    "089_athena_commando_f_swimmer": "Sun Strider",
    "090_athena_commando_m_swimmer": "Reef Ranger",
    "091_athena_commando_f_chef": "Grill Sergeant",
    "092_athena_commando_m_chef": "Beef Boss",
    "093_athena_commando_f_doctor": "Triage Trooper",
    "094_athena_commando_m_doctor": "Field Surgeon",
    "095_athena_commando_f_pilot": "Sky Stalker",
    "096_athena_commando_m_pilot": "Airheart",
    "097_athena_commando_f_rockerpunk": "Power Chord",
    "098_athena_commando_m_rockerpunk": "Stage Slayer"
}

# Back Bling mappings (AthenaBackpack)
BACK_BLINGS = {
    "001_athena_backpack_wings": "Love Wings",
    "002_athena_backpack_cape": "Cape",
    "003_athena_backpack_guitar": "Six String",
    "004_athena_backpack_jetpack": "Jetpack",
    "005_athena_backpack_shield": "Red Shield",
    "006_athena_backpack_shield": "Black Shield",
    "007_athena_backpack_bow": "Bow",
    "008_athena_backpack_quiver": "Quiver",
    "009_athena_backpack_backpack": "Backpack",
    "010_athena_backpack_wings": "Dark Wings",
    "011_athena_backpack_tank": "Fuel Tank",
    "012_athena_backpack_wings": "Frozen Shroud",
    "013_athena_backpack_cape": "Dusk Wings",
    "014_athena_backpack_wings": "Ravage",
    "015_athena_backpack_cape": "Wolfpack",
    "016_athena_backpack_wings": "Catalyst",
    "017_athena_backpack_cape": "Ragnarok Cape",
    "018_athena_backpack_wings": "Ice Mantle",
    "019_athena_backpack_cape": "Frozen Red Shield",
    "020_athena_backpack_wings": "Subjugator",
    "021_athena_backpack_cape": "Ominous Orb",
    "022_athena_backpack_wings": "Spectral Spine",
    "023_athena_backpack_cape": "Shattered Wing",
    "024_athena_backpack_wings": "Fallen Love Ranger Wings",
    "025_athena_backpack_cape": "Cuddle Bow",
    "026_athena_backpack_wings": "Royale Flags",
    "027_athena_backpack_cape": "Backup Plan",
    "028_athena_backpack_wings": "Webrella",
    "029_athena_backpack_cape": "Swag Bag",
    "030_athena_backpack_wings": "Brite Bag"
}

# Glider mappings (AthenaGlider)
GLIDERS = {
    "001_athena_glider_default": "Default Glider",
    "002_athena_glider_umbrella": "Umbrella",
    "003_athena_glider_snowflake": "Snowflake",
    "004_athena_glider_dragon": "Dragon Glider",
    "005_athena_glider_stealth": "Stealth Glider",
    "006_athena_glider_vintage": "Vintage Glider",
    "007_athena_glider_paper": "Paper Parasol",
    "008_athena_glider_cloud": "Cloudbreaker",
    "009_athena_glider_mechanical": "Mechanical Glider",
    "010_athena_glider_wings": "Winged Glider",
    "011_athena_glider_bat": "Bat Glider",
    "012_athena_glider_shark": "Shark Glider",
    "013_athena_glider_pizza": "Pizza Glider",
    "014_athena_glider_rainbow": "Rainbow Rider",
    "015_athena_glider_flames": "Flame Glider",
    "016_athena_glider_ice": "Frostwing",
    "017_athena_glider_lightning": "Storm Glider",
    "018_athena_glider_galaxy": "Galaxy Glider",
    "019_athena_glider_comet": "Comet Crasher",
    "020_athena_glider_rocket": "Rocket Glider",
    "021_athena_glider_balloon": "Balloon Glider",
    "022_athena_glider_kite": "Kite Glider",
    "023_athena_glider_parachute": "Parachute",
    "024_athena_glider_hang": "Hang Glider",
    "025_athena_glider_shuttle": "Space Shuttle",
    "026_athena_glider_plane": "Biplane",
    "027_athena_glider_helicopter": "Helicopter",
    "028_athena_glider_jetpack": "Jetpack Glider",
    "029_athena_glider_wings_angel": "Angel Wings",
    "030_athena_glider_wings_demon": "Demon Wings"
}

# Pickaxe mappings (AthenaPickaxe)
PICKAXES = {
    "001_athena_pickaxe_default": "Default Pickaxe",
    "002_athena_pickaxe_sleighhammer": "Sleigh Hammer",
    "003_athena_pickaxe_candycane": "Candy Cane Pickaxe",
    "004_athena_pickaxe_tactical": "Tactical Spade",
    "005_athena_pickaxe_scythe": "Reaper",
    "006_athena_pickaxe_guitar": "Axecalibur",
    "007_athena_pickaxe_disco": "Disco Brawl",
    "008_athena_pickaxe_medieval": "Crimson Axe",
    "009_athena_pickaxe_space": "Spectral Axe",
    "010_athena_pickaxe_valentine": "Tat Axe",
    "011_athena_pickaxe_scavenger": "Raider's Revenge",
    "012_athena_pickaxe_punk": "Power Chord",
    "013_athena_pickaxe_retro": "Disco Brawl",
    "014_athena_pickaxe_student": "Plunja",
    "015_athena_pickaxe_pirate": "Anchor",
    "016_athena_pickaxe_cowboy": "Trusty No. 2",
    "017_athena_pickaxe_ninja": "Crowbar",
    "018_athena_pickaxe_cyberscavenger": "Positron",
    "019_athena_pickaxe_plague": "Virulent Flames",
    "020_athena_pickaxe_carbide": "Onslaught",
    "021_athena_pickaxe_footballer": "Vuvuzela",
    "022_athena_pickaxe_soccer": "Goalbound",
    "023_athena_pickaxe_basketballplayer": "Slam Dunk",
    "024_athena_pickaxe_lifeguard": "Rescue Paddle",
    "025_athena_pickaxe_detective": "Magnifying Axe",
    "026_athena_pickaxe_western": "Pickaxe",
    "027_athena_pickaxe_vampire": "Vampiric",
    "028_athena_pickaxe_streetwear": "Whiteout",
    "029_athena_pickaxe_demon": "Malice Wings",
    "030_athena_pickaxe_clown": "Balloon Axe",
    "031_athena_pickaxe_cat": "Meow-scles",
    "032_athena_pickaxe_viking": "Permafrost",
    "033_athena_pickaxe_prisoner": "Molten Striker",
    "034_athena_pickaxe_banana": "Peel Out",
    "035_athena_pickaxe_fishstick": "Fish Pick",
    "036_athena_pickaxe_robot": "Mecha Team Leader",
    "037_athena_pickaxe_ice": "Frozen Axe",
    "038_athena_pickaxe_fire": "Molten Axe",
    "039_athena_pickaxe_military": "Combat Knife",
    "040_athena_pickaxe_biker": "Throttle",
    "041_athena_pickaxe_skier": "Ice Breaker",
    "042_athena_pickaxe_swimmer": "Coral Cruiser",
    "043_athena_pickaxe_chef": "Spatula",
    "044_athena_pickaxe_doctor": "Stethoscope",
    "045_athena_pickaxe_pilot": "Propeller Axe"
}